name: Production V2 Deployment - Hyphen UI

on:
  push:
    branches:
      - master-v2

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Generate build
        run: |
          yarn install
          yarn run build:prod
        env:
          CI: false
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          role-session-name: production-deploy
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # publish to production environment
      - name: Deploy to S3
        run: |
          aws s3 sync build s3://${{ secrets.S3_PROD_V2_BUCKET_NAME }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.S3_PROD_V2_CF_ID }} --paths /
          aws cloudfront create-invalidation --distribution-id ${{ secrets.S3_PROD_V2_CF_ID_2 }} --paths /
